name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, crystal: "1.20" }
          - { os: ubuntu-24.04-arm, crystal: "1.20" }
          - { os: macos-latest, crystal: "1.20" }

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}

      - name: Cache shards
        uses: actions/cache@v5
        with:
          path: |
            lib
            bin/ameba*
          key: ${{ matrix.os }}-shards-${{ hashFiles('**/shard.lock') }}

      - name: Install shards
        run: shards check || shards install

      # ---- Run tests on all Unix platforms

      - name: Setup debug environment (Unix)
        if: ${{ runner.os != 'Windows' }}
        run: mkdir -p bin/debug

      - name: Build Debug (Unix)
        if: ${{ runner.os != 'Windows' }}
        run: SHARDS_BIN_PATH=bin/debug shards build --debug

      - name: Run tests (Unix)
        if: ${{ runner.os != 'Windows' }}
        run: crystal spec

      # ---- Source lint and formatting check on Ubuntu / x86 only

      - name: Check formatting (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: crystal tool format; git diff --exit-code src

      - name: Build ameba  (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cp lib/ameba/bin/ameba.cr bin && crystal build -o bin/ameba bin/ameba.cr

      - name: Run static code analysis (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: bin/ameba src/
